### ISSUE TITLE
not working on openSUSE Leap Version 15.4

### ISSUE THREAD

**Issue by nichtgedacht** [Pulsar07/JetiLogAnalytics#1]
db@zen:/data/JetiLogAnalytics/bin> ./JetiLogAnalytics.sh -nogui /home/db/Dokumente/Logs2
JetiLogAnalytics (JLA) Version: 0.2.5
23.05.31-11:24:07:024 SEVERE [JetiLogAnalytics.main()]: unexpected error:
java.lang.NullPointerException
        at de.so_fa.modellflug.jeti.jla.JetiLogAnalytics.main(JetiLogAnalytics.java:146)

**Comment by Pulsar07** [comment]
the exceeption is an error in the error handling ;-)), which is solved in the 0.2.6 version. 
Nevertheless this does not solve your problem, you have to give the log directory with the -d parameter:
> ./JetiLogAnalytics.sh -nogui -d /home/db/Dokumente/Logs2

**Comment by nichtgedacht** [comment]
You are right. Forgot the "--dir"

For using the GUI mode the module path must be given on openSUSE like:

java --module-path "/usr/share/java/openjfx:/usr/lib64/java/openjfx"  --add-modules ALL-MODULE-PATH -jar /data/JetiLogAnalytics/bin/JetiLogAnalytics.jar DE
